spring:
  application:
    name: emailapp
  datasource:
    url: jdbc:postgresql://localhost:5432/emailapp
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_GMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    verify:
      host: http://localhost:8080

server:
  port: 8080